### ISSUE TITLE
Flowser not displaying emulator transactions and some contracts

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflowser/flowser#157] opened 2023-01-10 22:03 UTC
When executing transaction on the emulator (run as  Flowser process) they execute, however do not display in the Flowser UI under the Transactions tab. 

Also, when adding a contract to an account, the new contract is not displayed in the Contracts tab.

Flowser is able to detect blocks, events, and accounts, but is having issues with transactions and contracts.

**To Reproduce**
1. Start Flowser `flow flowser`
2. Execute a transaction to add a contract to an account.
3. Notice the transaction and newly added contract not appear in Flowser UI.

**Expected behavior**

Transactions and contracts appear in the Flowser UI.

**Desktop (please complete the following information):**

Flow CLI `v0.43.2`
OS: MacOS Monterey

**Comment by bartolomej** [comment] 2023-01-12 12:54
@JeffreyDoyle I tried reproducing that. When running the emulator as a Flowser process, I encountered this error when executing deploy contract transaction (happened when I tried with Flow CLI or with Flowser send transaction UI):

```
> flow accounts add-contract ./contracts/HelloWorld.cdc
Transaction ID: a9ad1e2c390d977ae1170927f8b933389442cdd81a1dcc8842b76a6a813d3602
❌ Command Error: failed to submit transaction: client: rpc error: code = Internal desc = unknown reference block
```

![Screenshot 2023-01-12 at 13 46 45](https://user-images.githubusercontent.com/36109955/212070081-eadc2afc-e74c-484b-a915-c223d9f90859.png)

Looks like the transaction doesn't even get submitted to the network.

Here is the transaction code I used:
```cdc
transaction {

  prepare(acct: AuthAccount) {
  let code = "70756220636F6E74726163742054657374207B0D0A20202020707562206C6574206D6573736167653A20537472696E670D0A0D0A20202020696E6974286D6573736167653A20537472696E6729207B0D0A202020202020202073656C662E6D657373616765203D206D6573736167650D0A202020207D0D0A7D".decodeHex()
    acct.contracts.add(
      name: "Test",
      code: code,
      message: "I'm a new contract in an existing account"
    )
  }
}
```

You said the transaction was executed successfully for you? Did you not run into this issue? Could you share the code that you used?

Note that I was able to successfully execute and see the contract when running the emulator manually (outside Flowser process).

**Comment by bartolomej** [comment] 2023-06-22 09:36
Just tested the usage of the following Flow CLI commands again:
- `flow accounts add-contract`
- `flow accounts update-contract`
- `flow accounts remove-contract`

Thier effects are all properly reflected in Flowser app, so closing this issue.

**Closed by bartolomej** 2023-06-22 09:36 UTC
Labels: bug, feedback
